import React from 'react'
import Navbar from '../../components/Navbar/Navbar'
import MediaFooter from '../../components/Footer/MediaFooter'
import { Footer } from '../../components/Footer/Footer'
import MediaNavbar from '../../components/MediaNavbar/MediaNavbar'

function TermCondition() {
  return (
    <div>
        <MediaNavbar />
        <Navbar />
        <div className='container-fluid'>
           <div align='center'><h4 style={{padding:'40px',fontWeight:'650'}}>Term & Conditions</h4></div> 
           <div style={{padiing:'40px'}}><p>
           PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE USING possindia.in (‘Website’) & MOBILE APPLICATION – ‘Possindia FOR HAPPY PETS’ (‘App’) TOGETHER AS (‘PLATFORM’). THESE TERMS OF USE (HEREINAFTER ‘Terms of Use’) GOVERN YOUR ACCESS TO AND USE OF THE WEBSITE AND APP. THE WEBSITE AND APP ARE AVAILABLE FOR YOUR USE ONLY ON THE CONDITION THAT YOU AGREE TO THE TERMS OF USE SET FORTH BELOW. IF YOU DO NOT AGREE TO ALL OF THE TERMS OF USE, DO NOT ACCESS OR USE THE PLATFORM. BY IMPLICITLY OR EXPRESSLY ACCEPTING THE TERMS OF USE, YOU ALSO ACCEPT AND AGREE TO BE BOUND BY Poss POLICIES (INCLUDING BUT NOT LIMITED TO PRIVACY POLICY) AS AMENDED FROM TIME TO TIME AND AVAILABLE ON THE PLATFORM. BY ACCESSING OR USING THE PLATFORM, YOU AND THE ENTITY YOU ARE AUTHORISED TO REPRESENT SIGNIFY YOUR AGREEMENT TO BE BOUND BY THE TERMS OF USE.
YOU ARE RESPONSIBLE TO ENSURE THAT YOUR ACCESS TO THE PLATFORM AND MATERIAL AVAILABLE ON OR THROUGH IT ARE LEGAL IN EACH GURUGRAM,HARYANA  JURISDICTION, IN OR THROUGH WHICH YOU ACCESS OR VIEW THE PLATFORM OR SUCH MATERIAL
1) Membership/Registration Eligibility
Use of the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are “incompetent to contract” within the meaning of the Indian Contract Act, 1872 are not eligible to use the Platform. If you are a minor i.e., under the age of 18 years, you shall not be able to register yourself as a user of the Platform and shall not transact on or use the Platform. As a minor, if you wish to use or transact on Platform, such use or transaction may be made by your legal guardian or parents who shall be registered on the Platform. Possindia reserves the right to terminate your membership and/or refuse to provide you with access to the Platform if it is brought to Possindia’s notice or if it is discovered that you are under the age of 18 years and/or are incompetent to contract as provided under the Indian Contract Act, 1872 <br />
2) SCOPE AND BACKGROUND
This document is an electronic record in terms of Information Technology Act, 2000 and rules made thereunder as applicable and the amended from time to time, pertaining to electronic records. This electronic record is generated by a computer system and does not require any physical or digital signatures.
For the purpose of the Terms of Use, wherever the context so requires “you” or “user”, it shall mean any natural or legal person who has agreed to become a customer on the Platform by providing your information and data while registering on the Platform as a registered user using the computer and mobile systems.
Possindia permits the user to surf the Website and App and/or making purchases and/or subscribing to services through Website and/or App only after registering yourself on the Website and/or App.
When you use any of our services and/or purchase any of the products through the Website or App, including but not limited to, product reviews, service reviews etc., you will be subject to the Rules, Guidelines, Policies, Terms and Conditions applicable to such services and products, and they shall be deemed to be incorporated into the Terms of Use and shall be considered as part and parcel of the Terms of Use. We reserve the right, at our sole discretion, to change, modify, add or remove portions of the Terms of Use, at any time without any prior written intimation. It shall be your responsibility to review the Terms of Use periodically for any updates / changes. Your continued use of the Website and/or App following the posting of changes shall imply and mean that you accept and agree to the revisions / changes. As long as you comply with the Terms of Use, we grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Platform and subscribe to services and purchase of products.
ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR EXPLICIT CONSENT TO ALL THE TERMS AND CONDITIONS UNDER THE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. <br />
3) Your Account and Registration Obligations
If you use the Platform, you shall solely be responsible for maintaining the confidentiality of your display name / user name and password, used for logging in into your account on the Platform and you shall solely be responsible for all activities that shall take place under your display name / user name and password. We shall not assume and held liable/responsible in any manner whatsoever for any of the activities done using your account. You agree that if you provide any information which is untrue, inaccurate, not current or incomplete or we have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the Terms of Use, we reserve the right to indefinitely suspend or terminate or block access to your account and refuse to provide you access to your account. <br />
4) Communications
When you use the Platform or send emails or other data, information or communication to us, you agree and understand that you are communicating with us through electronic records and further you consent to receive communications via electronic records from us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise. <br />
5) Charges / Fees
Membership / creating an Account on the Platform is free as Poss does not charge any fee for browsing on the Platform. In particular, possindia may at its sole discretion can introduce new services/products and modify some or all of the existing services/products offered on the Platform. In such an event possindia reserves the right to introduce fees for the new services/products offered or amend/introduce fees/prices for existing services/products, in its sole discretion. possindia reserves the right to change its fees/prices from time to time. Changes to the fees/prices shall be posted on the Platform and such changes shall automatically become effective immediately after they are posted on the Platform. Unless otherwise stated, all fees/prices shall be quoted in Indian Rupees (INR). You shall be solely responsible for compliance of all applicable laws including those in India for making payments to possindia. <br />
6) Use of the Platform
You agree, undertake and confirm that your use of Platform shall be strictly governed by the Terms of Use, including Rules, Guidelines, Policies, Terms and Conditions applicable to such services and products: <br />
(a) You shall not host, display, upload, modify, publish, transmit, update or share any information which:
belongs to another person and to which you are not authorized to
is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilia, libellous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to “indecent representation of women” within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;
is misleading in any way
is offensive to the online community, such as sexually explicit content, or content that promotes obscenity, paedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual
harasses or advocates harassment of another person;
involves the transmission of “junk mail”, “chain letters”, or unsolicited mass mailing or “spamming”;
promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libellous;
infringes upon or violates any third party’s rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person’s name, email address, physical address or phone number) or rights of publicity];
promotes an illegal or unauthorized copy of another person’s copyrighted work such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;
contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);
provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;
provides instructional information about illegal activities such as making or buying illegal weapons, violating someone’s privacy, or providing or creating computer viruses;
contains video, photographs, or images of another person (with a minor or an adult).
tries to gain unauthorized access or exceeds the scope of authorized access to the Platform or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Platform or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;
solicits gambling or engages in any gambling activity which we, in our sole discretion, believes is or could be construed as being illegal;
interferes with another user’s use and enjoyment of the Platform or any other individual’s user and enjoyment of similar services;
refers to any website or URL that, in our sole discretion, contains material that is inappropriate for the Platform or any other website, contains content that would be prohibited or violates the letter or spirit of the Terms of Use.
harm minors in any way;
infringes any patent, trademark, copyright or other proprietary rights or third party’s trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen products;
violates any law for the time being in force;
deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;
impersonate another person;
contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;
threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offense or prevents investigation of any offense or is insulting any other nation.
shall not be false, inaccurate or misleading;
shall not, directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force.
shall not create liability for Us or cause Us to lose (in whole or in part) the services of our internet service provider (“ISPs”) or other suppliers
            </p></div>
        </div>
        <Footer />

        <MediaFooter />

    </div>
  )
}

export default TermCondition